label variable Lowner "Owner"
label variable Lmanager "Manager"
label variable Lonly_owner "Only owner"
label variable Lonly_manager "Only manager"
label variable Lboth "Both"
label variable Lowner_comlang "...with common language"
label variable Lmanager_comlang "...with common language"
label variable Llanguage "...with same ethnicity"
